# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=26.1.2
	loader_version=0.19.3

# Mod Properties
	mod_version = 0.1.6-beta
	maven_group = dev.alexjf
	archives_base_name = homegrown

# Dependencies
	fabric_api_version=0.155.2+26.1.2
